spring:
  application:
    name: paas-ta-container-platform-pipeline-ui
  http:
    multipart:
      maxFileSize: 1000Mb
      maxRequestSize: 1000Mb

server:
  tomcat:
    uri-encoding: UTF-8
---
spring:
  profiles:
    active: prod

server:
  port: ${PORT:8084}
  error:
    whitelabel:
    enabled: false

logging:
  level:
    ROOT: INFO
  path: classpath:logback-spring.xml
  file: logs/application.log

commonApi:
  url: ${CONTAINER_PLATFORM_PIPELINE_COMMON_API_URI}
  authorization:
    id: "admin"
    password: "PaaS-TA"

deliveryPipelineApi:
  url: ${CONTAINER_PLATFORM_PIPELINE_API_URI}
  authorization:
    id: "admin"
    password: "PaaS-TA"

inspectionApi:
  url: ${CONTAINER_PLATFORM_PIPELINE_INSPECTION_API_URI}
  authorization:
    id: "admin"
    password: "PaaS-TA"

keycloak:
  oauth:
    info:
      uri: ${KEYCLOAK_URI}/auth/realms/cp-realm/protocol/openid-connect/userinfo
    token:
      check:
        uri: ${KEYCLOAK_URI}/auth/realms/cp-realm/protocol/openid-connect/token/introspect
      access:
        uri: ${KEYCLOAK_URI}/auth/realms/cp-realm/protocol/openid-connect/token
    logout:
      url: ${KEYCLOAK_URI}/auth/realms/cp-realm/protocol/openid-connect/logout
    authorization:
      uri: ${KEYCLOAK_URI}/auth/realms/cp-realm/protocol/openid-connect/auth
    client:
      id: {KEYCLOAK_CLIENT_ID}
      secret: ${KEYCLOAK_SECRET_ID}
      scope:
      role: ${KEYCLOAK_ROLE_NAME}



config:
  server:
    url: ${CONFIG_SERVER_URI}