spring:
  application:
    name: paas-ta-container-platform-pipeline-ui
  http:
    multipart:
      maxFileSize: 1000Mb
      maxRequestSize: 1000Mb

server:
  tomcat:
    uri-encoding: UTF-8
---
spring:
  profiles:
    active: prod

server:
  port: ${PORT:8084}
  servlet:
    session:
      cookie:
        name: PIPELINESESSION

logging:
  level:
    ROOT: INFO
  path: classpath:logback-spring.xml
  file: logs/application.log

commonApi:
  url: ${CONTAINER_PLATFORM_PIPELINE_COMMON_API_URI}
  authorization:
    id: "admin"
    password: "PaaS-TA"

deliveryPipelineApi:
  url: ${CONTAINER_PLATFORM_PIPELINE_API_URI}
  authorization:
    id: "admin"
    password: "PaaS-TA"

inspectionApi:
  url: ${CONTAINER_PLATFORM_PIPELINE_INSPECTION_API_URI}
  authorization:
    id: "admin"
    password: "PaaS-TA"

keycloak:
  oauth:
    info:
      uri: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_CP_REALM}/protocol/openid-connect/userinfo
    token:
      check:
        uri: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_CP_REALM}/protocol/openid-connect/token/introspect
      access:
        uri: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_CP_REALM}/protocol/openid-connect/token
    logout:
      url: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_CP_REALM}/protocol/openid-connect/logout
    authorization:
      uri: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_CP_REALM}/protocol/openid-connect/auth
    client:
      id: ${KEYCLOAK_CP_CLIENT_ID}
      secret: ${KEYCLOAK_CP_CLIENT_SECRET}
      scope:
      role: ${KEYCLOAK_CLUSTER_ADMIN_ROLE}



config:
  server:
    url: ${CONFIG_SERVER_URL}
