spring:
  application:
    name: paas-ta-container-platform-pipeline-api
  http:
    multipart:
      maxFileSize: 1000Mb
      maxRequestSize: 1000Mb
---
spring:
  profiles:
    active: prod

server:
  port: 8082

logging:
  level:
    ROOT: INFO
  path: classpath:logback-spring.xml
  file: logs/application.log

commonApi:
  url: ${CONTAINER_PLATFORM_PIPELINE_COMMON_API_URI}
  authorization:
    id: "admin"
    password: "PaaS-TA"

inspectionApi:
  url: ${CONTAINER_PLATFORM_PIPELINE_INSPECTION_API_URI}
  authorization:
    id: "admin"
    password: "PaaS-TA"

ci:
  server:
    credentials:
      scope: "GLOBAL"
      url: /credentials/store/system/domain/_
      className: "com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl"

harbor:
  server:
    api:
      url: "${HARBOR_API_URL}"
    admin:
      username: "${HARBOR_ADMIN_USER}"
      password: "${HARBOR_ADMIN_PASSWORD}"
delivery:
  pipelineUI:
    log:
      url: ${CONTAINER_PLATFORM_PIPELINE_UI_URI}/dashboard/{SERVICE_INSTANCE_ID}/pipelines/{PIPELINE_ID}/jobs/{JOB_ID}/{JOB_TYPE}
keycloak:
  admin:
    api:
      url: ${KEYCLOAK_URL}
      grant:
        type: password
      username: ${KEYCLOAK_ADMIN_ID}
      password: ${KEYCLOAK_ADMIN_PASSWORD}
      client:
        id: admin-cli
    token:
      url: "/realms/master/protocol/openid-connect/token"
    users:
      url: "/admin/realms/{realms}/users"
