spring:
  application:
    name: paas-ta-container-platform-pipeline-service-broker
---
spring:
  profiles:
    active: prod
  primary:
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mysql://${DATABASE_URL}/pipeline_broker?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
      username: ${DATABASE_USER_ID}
      password: ${DATABASE_USER_PASSWORD}
      pool-name: "Broker-DB"
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    database: "mysql"
    show-sql: true

server:
  port: ${PORT:8083}

cf:
  api:
    url: ${CF_API_URL}

logging:
  level:
    ROOT:
      org:
        openpaas:
          servicebroker:
            controller: INFO
        paasta:
          servicebroker:
            deliverypipeline:
              service: INFO

service:
  dashboard:
    url: ${DASHBOARD_URL}

paasta:
  delivery:
    pipeline:
      api:
        url: ${CONTAINER_PLATFORM_PIPELINE_COMMON_API_URI}
        username: admin
        password: PaaS-TA
ci:
  server:
    shared:
      urls: '["${CI_SERVER_URL}"]'
serviceDefinition:
  id: af86588c-6212-11e7-907b-b6006ad3dps0
  name: container-platform-pipeline
  desc: "A paasta container platform pipeline service for application development.provision parameters : parameters {owner : owner}"
  bindable: false
  planupdatable: false
  plan1:
    id: a5930564-6212-11e7-907b-b6006ad3dps1
    name: container-platform-pipeline-shared
    desc: "This is a shared service plan. All services are created equally."
    type: A

keycloak:
  admin:
    client:
      grantType: password
      username: ${KEYCLOAK_ADMIN_ID}
      password: ${KEYCLOAK_ADMIN_PASSWORD}
      serverUrl: ${KEYCLOAK_URL}
      realm: master
      clientId: admin-cli
    cp:
      realm: ${KEYCLOAK_CP_REALM}
      IdentityProviderId: ${KEYCLOAK_IDENTITY_PROVIDER_ID}
      clusterAdminGroup: ${KEYCLOAK_CLUSTER_ADMIN_GROUP}
      clusterAdminRole: ${KEYCLOAK_CLUSTER_ADMIN_ROLE}

